Add timeout for fluentd validate command run
vmware/kube-fluentd-operator pull request #156
Opened 2020-11-26 04:18 UTC by zhangheng1442

If there is wrong fluentd config,fluentd validate command may stuck,case fluentd.conf file can not be created.
for example,there is an unreachble elasticsearch server , fluentd will try to connect to the elasticserver forerver,and because the "-qq" ,there is no output in the debug level log
the fluentd pod crash,because the fluentd.conf was not create by the config-reloader.
remove the "-qq" and add 30s timeout for the fluentd validata command run,so the config-reloader won't stuck,and the fluentd can run

2021-02-06 19:55 UTC, Cryptophobia commented
@zhangheng1442 , can you rebase with latest master branch?

2021-02-06 19:58 UTC, Cryptophobia commented
I'm not sure we want to remove `-qq` , maybe it is best to use the warn level for now `-q`? Will the elasticsearch connection errors display in log leve warn? 

Ideally, we need to make log-level configurable with an ENV var in the helm charts.

The reason `-qq` is nice is because too many log lines in high-scale environments where fluentd-operator.

2021-02-11 14:32 UTC, Cryptophobia commented
This is also kind of related to your issue with connection to elasticsearch: https://github.com/vmware/kube-fluentd-operator/issues/153

Seems it takes 15 tries to connect and each one takes a long time and does not actually return any errors.

2021-02-15 10:34 UTC, viveksyngh requested changes
Please rebase it with master

2021-02-15 10:34 UTC, viveksyngh commented on config-reloader/util/util.go
> +			err = errors.New("process killed as timeout reached after 10s")
same as above

2021-02-16 06:54 UTC, viveksyngh commented
@zhangheng1442 could you please rebase this branch ?

2021-04-08 16:34 UTC, Cryptophobia commented
@zhangheng1442 we appreciate your contribution! Thank you for making KFO `v1.14.0` possible! It was merged in two PRs: here https://github.com/vmware/kube-fluentd-operator/pull/180 and here https://github.com/vmware/kube-fluentd-operator/pull/193.

In https://github.com/vmware/kube-fluentd-operator/pull/193, we tested and decide to go with `-q` as that will still produce warning messages during fluentd validation which can be verify helpful although config-reloader may be a bit more noisy. Since the timeout will quit the command now the golang thread will exit no matter if the validation is stuck or not, which is the behavior that we want.

2021-04-08 16:34 UTC, closed without merging