Add automatic releases to Github actions
vmware/kube-fluentd-operator pull request #330
Opened 2022-06-02 15:03 UTC by gga-kialo

From what I can tell, releases used to be created manually by @Cryptophobia and then @javiercri took over, but has not been including the Helm chart build in them, even though it is still referenced in the README.md file. I suggest creating releases automatically whenever a new tag is pushed to origin (assuming tags are only used for versions). This PR is a proof of concept. You can go fancier with automatic release notes or extracting the version of the build artifact `log-router-0.4.0.tgz` from `charts/log-router/Chart.yaml`.
Beware that the `create-release` step does not belong in the `release-workflow`, which may cause confusion. Adapt if desired.

Signed-off-by: Guillermo Guirao Aguilar <gga@kialo.com>

2022-07-07 09:11 UTC, javiercri requested changes

2022-07-07 09:11 UTC, javiercri commented on .github/workflows/build-workflow.yaml
> +        working-directory: charts/log-router
could you add this in the release-workflow instead of build-workflow?
The release-workflow will work just for tag who is what we want

2022-07-07 09:14 UTC, javiercri requested changes

2022-07-07 09:14 UTC, javiercri commented on .github/workflows/build-workflow.yaml
>          run: |
Could you add this in release-workflow instead of build-workflow?

2022-09-20 08:24 UTC, gga-kialo commented
@javiercri, I'm not sure if anything is missing from my side for this PR to get reviewed again and merged.

2022-10-13 08:32 UTC, javiercri approved these changes
LGTM

2022-10-13 08:33 UTC, merged