Reload Configuration only when a pod matching the label set in mounted-file is created or deleted
vmware/kube-fluentd-operator pull request #347
Opened 2022-10-20 01:07 UTC by huskykurt

According to the issue comments ([comment1](https://github.com/vmware/kube-fluentd-operator/issues/289#issuecomment-985904900), [comment2](https://github.com/vmware/kube-fluentd-operator/issues/289#issuecomment-1141027421)) the existing solution caused too many configuration reloads.
This is because the configuration reload occurred whenever every pod was created (or deleted). So it is not affordable for a large cluster.
So, make the configuration reload only when a pod with the label set in the mounted-file is created (or deleted).

2022-10-26 08:34 UTC, huskykurt commented
Hello @javiercri. How do I get a review for this PR? I looked at the [CLA FAQ](https://cla.vmware.com/faq) and they said that if I send a PR, I will receive a comment requesting the CLA, but there is no comment.

2022-12-13 15:39 UTC, javiercri commented
First sorry for the late reply.
Could you fix the conflicts here @huskykurt, and I can approve it.
Thanks in advance!

2022-12-13 15:42 UTC, javiercri requested changes

2022-12-15 00:14 UTC, huskykurt commented on config-reloader/util/util.go
> +func Match(labels map[string]string, contLabels map[string]string, contName string) bool {
@javiercri I added a test for this function

2022-12-15 08:22 UTC, javiercri approved these changes
LGTM

2022-12-15 10:00 UTC, merged